Repository pallets/click, pull requests merged in 2020-10, with the labels that each got.

#1622 Redesign Completion System
  CHANGES.rst
  docs/api.rst
  docs/bashcomplete.rst
  docs/conf.py
  docs/index.rst
  docs/shell-completion.rst
  examples/bashcompletion/README
  examples/bashcompletion/bashcompletion.py
  examples/completion/README
  examples/completion/completion.py
  examples/completion/setup.py
  requirements/dev.txt
  requirements/docs.in
  requirements/docs.txt
  src/click/_bashcomplete.py
  src/click/core.py
  src/click/shell_completion.py
  src/click/types.py
  tests/test_bashcomplete.py
  tests/test_compat.py
  tests/test_shell_completion.py
Labels: f:completion

#1679 pass extra context settings to completion
  CHANGES.rst
  src/click/core.py
  src/click/shell_completion.py
  tests/test_shell_completion.py
Labels: f:completion

#1683 swap order of completion instruction
  CHANGES.rst
  docs/shell-completion.rst
  src/click/shell_completion.py
  tests/test_shell_completion.py
Labels: f:completion

#1535 Make ParameterSource a proper Python 3 Enum subclass.
  CHANGES.rst
  docs/advanced.rst
  docs/api.rst
  src/click/core.py
  tests/test_context.py
  tests/test_imports.py
Labels: f:parameters

#1606 boolean type strips space before converting
  CHANGES.rst
  src/click/types.py
  tests/test_options.py
Labels: f:parameters

#1549 show_default looks at default_map
  CHANGES.rst
  src/click/core.py
  tests/test_options.py
Labels: f:help, f:parameters

#1618 option without value can prompt or use default
  CHANGES.rst
  docs/options.rst
  src/click/core.py
  src/click/parser.py
  tests/test_options.py
  tests/test_termui.py
Labels: f:prompt

#1517 With prompt, if no input is specified, the return value is not converted to the requested type
  CHANGES.rst
  src/click/termui.py
  tests/test_utils.py
Labels: f:prompt

#1697 Added examples of default to boolean flags section
  docs/options.rst
Labels: docs
