Repository pallets/click, pull requests merged in 2021-05, with the labels that each got.

#1887 Update typing
  CHANGES.rst
  setup.cfg
  src/click/__init__.py
  src/click/core.py
  src/click/parser.py
  src/click/types.py
Labels: typing

#1908 Update typing
  CHANGES.rst
  setup.cfg
  src/click/__init__.py
  src/click/core.py
  src/click/parser.py
  src/click/types.py
Labels: typing

#1909 ProgressBar inherits Generic
  CHANGES.rst
  src/click/_termui_impl.py
  src/click/termui.py
Labels: typing

#1894 Fix minor mistake in 8.0 changelog
  CHANGES.rst
Labels: docs

#1912 update changelog about version_option
  CHANGES.rst
  src/click/decorators.py
Labels: docs

#1913 detect type from flag_value
  CHANGES.rst
  src/click/core.py
  src/click/types.py
  tests/test_options.py
Labels: f:parameters

#1914 document values passed to types
  CHANGES.rst
  docs/parameters.rst
Labels: docs

#1928 Correct docstring reference
  src/click/core.py
Labels: docs
