Repository pallets/click, pull requests merged in 2024-12, with the labels that each got.

#2586 Break up arguments section
  docs/arguments.rst
  docs/handling-files.rst
  docs/index.rst
  docs/parameters.rst
  src/click/types.py
Labels: docs

#2804 Correct click.edit typing
  CHANGES.rst
  src/click/_termui_impl.py
  src/click/termui.py
Labels: typing

#2803 Improve typing on Windows
  src/click/_compat.py
  src/click/_termui_impl.py
  src/click/_winconsole.py
  tox.ini
Labels: windows, typing
